String l1 = "Un-Frágil-Acontecimiento:~#  Su equipo ha sido infectado con una serie de frágiles acontecimientos";
String l2 = "                             de la vida cotidiana.";
String l3 = "Un-Frágil-Acontecimiento:~#  Esta es una invitación a contemplar.";
String l4 = "Un-Frágil-Acontecimiento:~#  Si necesita volver desesperadamente a su rutina, use las flechas para";
String l5 = "                             elegir 'volver' y presione ENTER para continuar.";
String l6 = "     seguir  /  volver";
String l7 = "Descripción:      Un frágil acontecimiento deriva de Un tejido de flujos y el hilo";
String l8 = "                  rebelde.  La pausa como propuesta de acto artístico en la Ciudad";
String l9 = "                  de México. [Versión 1.0] (c)2017-2021 AlejandroVCabrera CC BY-SA.";
String l10= "Agradecimientos:  P3ltr3, Alejandro Vargas Becerril, Araceli Cabrera Torres, Niñx";
String l11= "                  Caín, Brenda Martínez, Kaathlen Coello , Luis Romero, Alejandro";
String l11Kaath= "Kaathlen Coello";
String l12= "                  Mendez, Guillermo Sánchez, Eunice Vergara, Alberto Sierra, Eli-";
String l13= "                  sa Viramontes, Sam, Emi, y a ti que estás leyendo esto.";
String l14= "                  (Agradecimientos al Centro Multimedia del Centro Nacional de las";
String l15= "                  Artes por el apoyo otorgado).";
String l16= "Un-Frágil-Acontecimiento:~#  Toma un respiro. (  )                       (ENTER para continuar...)";
String l17= "Un-Frágil-Acontecimiento:~#  ¿Percibes el calor que emana del teclado? ¿Cómo se siente? (  )";
String l18= "Un-Frágil-Acontecimiento:~#  ¿Ves polvo en su superficie? ¿Qué hay de la grasa de tus dedos? (  )"; //92 caracteres
String l19= "Un-Frágil-Acontecimiento:~#  ¿Puedes distinguir tus huellas digitales sobre las teclas? (  )";
String l20= "Un-Frágil-Acontecimiento:~#  Escucha el sonido que hacen al teclear... (  )"; //NO ENTER
String l21= "Un-Frágil-Acontecimiento:~#  ¿Puedes ver tu reflejo en la pantalla?";
String l22= "         sí    /    no";
String l23= "Un-Frágil-Acontecimiento:~#  ¿Lo viste?";
String l24= "         sí    /    no";
String l25= "Un-Frágil-Acontecimiento:~#  ¿Qué más puedes ver? (  )"; // 49 caracteres (588px)
String l26= "Un-Frágil-Acontecimiento:~#  Respira sobre la pantalla, haz que tu aliento la empañe.  No verás tu";
String l27= "                             reflejo, pero sí una manifestación de tu vida. (  )"; //75 caracteres (900px)
String l28= "Un-Frágil-Acontecimiento:~#  ¿Acaso le tememos a la pausa? (  )"; // 58 caracteres (696px)
String l29= "Un-Frágil-Acontecimiento:~#  Hay muchos más motivos para ejercerla de lo que creemos, sólo hay que";
String l30= "                             abrirse a percibir; a contemplar. (  )";
String l31= "Un-Frágil-Acontecimiento:~#          CUANDO";
String l32= "                                EL HUMO DEL TABACO";
String l33= "                                 TAMBIÉN SE NOTA";
String l34= "                                   DE LA BOCA";
String l35= "                                  QUE LO EXHALA";
String l36= "                                 LOS DOS OLORES";
String l37= "                                  SE CASAN POR";
String l38= "                                   INFRA-LEVE";
String l39= "                                   Infra-leve, Marcel Duchamp. (  )      (ENTER para continuar...)";
String l40= "Un_Frágil_Acontecimiento.jpg";
String l41= "Mira_a_través_de_la_ventana.jpg";
